import { supabase } from "./supabase";
import { Recipe } from "./gemini_recipes";

export interface SavedRecipe {
  id: string;
  user_id: string;
  name: string;
  ingredients: string[];
  instructions: string[];
  image_url: string | null;
  meal_type: string | null;
  diet_type: string | null;
  cuisine_type: string | null;
  spice_level: string | null;
  prep_time: number;
  created_at: string;
}

/**
 * Saves a generated recipe into the `recipes` table, then marks it
 * as a favourite in the `favorites` table.
 *
 * Uses upsert on (user_id, name) so re-selecting the same recipe
 * never creates a duplicate row.
 *
 * Returns the saved recipe's UUID.
 */
export async function saveRecipe(
  recipe: Recipe,
  preferences: {
    meal_type?: string;
    diet_type?: string;
    cuisine_type?: string;
    spice_level?: string;
  } = {},
  imageUrl: string | null = null,
): Promise<string> {
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) throw new Error("Not authenticated");

  // 1. Check if recipe already exists for this user
  let recipeId: string;

  const { data: existingRecipe } = await supabase
    .from("recipes")
    .select("id")
    .eq("user_id", user.id)
    .eq("name", recipe.name)
    .maybeSingle();

  if (existingRecipe) {
    recipeId = existingRecipe.id;
  } else {
    // Insert new recipe
    const { data: newRecipes, error: recipeError } = await supabase
      .from("recipes")
      .insert({
        user_id: user.id,
        name: recipe.name,
        ingredients: recipe.ingredients,
        instructions: recipe.instructions,
        prep_time: recipe.prep_time,
        image_url: imageUrl,
        meal_type: preferences.meal_type ?? null,
        diet_type: preferences.diet_type ?? null,
        cuisine_type: preferences.cuisine_type ?? null,
        spice_level: preferences.spice_level ?? null,
      })
      .select("id");

    if (recipeError || !newRecipes || newRecipes.length === 0) {
      console.error("Error saving recipe:", JSON.stringify(recipeError, null, 2));
      // Don't throw a fatal error, just gracefully return a dummy ID or fail
      // so the user can still proceed to the recipe page
      console.warn("Falling back, could not save to DB.");
      return "temp-id-" + Date.now();
    }
    recipeId = newRecipes[0].id;
  }

  // Removed the automatic addition to favorites so users can manually favorite them on the home screen.
  return recipeId;
}

/**
 * Returns all recipes generated by the user (history), newest first.
 */
export async function getHistoryRecipes(limit = 50): Promise<SavedRecipe[]> {
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from("recipes")
    .select("*")
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) {
    console.error("Error fetching history recipes:", error);
    throw new Error("Failed to fetch history recipes");
  }

  return (data ?? []) as SavedRecipe[];
}

export async function toggleFavorite(recipeId: string, isFavorite: boolean): Promise<void> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return;

  if (isFavorite) {
    // Add to favorites
    await supabase.from("favorites").insert({ user_id: user.id, recipe_id: recipeId });
  } else {
    // Remove from favorites
    await supabase
      .from("favorites")
      .delete()
      .eq("user_id", user.id)
      .eq("recipe_id", recipeId);
  }
}

/**
 * Returns a Set of recipe IDs that the user has favorited.
 */
export async function getFavoriteRecipeIds(): Promise<Set<string>> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return new Set();

  const { data } = await supabase
    .from("favorites")
    .select("recipe_id")
    .eq("user_id", user.id);

  return new Set((data ?? []).map((row) => row.recipe_id));
}

/**
 * Returns the current user's saved (favourited) recipes, newest first.
 */
export async function getSavedRecipes(limit = 20): Promise<SavedRecipe[]> {
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from("favorites")
    .select("recipes(*)")
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) {
    console.error("Error fetching saved recipes:", error);
    throw new Error("Failed to fetch saved recipes");
  }

  // Unwrap the nested recipes object
  return (data ?? [])
    .map((row: any) => row.recipes)
    .filter(Boolean) as SavedRecipe[];
}

/**
 * Returns true if a recipe (matched by name) is already saved by the user.
 */
export async function isRecipeSaved(recipeName: string): Promise<boolean> {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return false;

  const { data } = await supabase
    .from("recipes")
    .select("id")
    .eq("user_id", user.id)
    .eq("name", recipeName)
    .maybeSingle();

  return data !== null;
}
